config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]

  
  
  resources :wikis do
      resources :collaborators, only: [:create, :destroy]
   end

  resources :downgrades

  devise_for :users
  
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  
  
  
  
  default_scope { order('created_at DESC') }
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
 

  
  def index
     @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
    
    
  end

  def new
    @wiki = Wiki.new
  end
  
  def create 
    @wiki = Wiki.new(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    
    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Wiki was not saved. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
    
    
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    
    
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "Wiki could not be updated. Please try again."
      render :edit
    end
  end    
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
    end
  end

  def authorize_user
     unless current_user.admin?
       flash[:alert] = "You must be an admin to do that."
       redirect_to wikis_path
     end
  end
  
  

end#end of ends

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/edit.html.erb
<div class="container">
    <div class="jumbotron">
        <h1>Edit Wiki</h1>
           
             <%= form_for @wiki do |f| %>
               <div class="form-group">
                 <%= f.label :title %>
                 <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
               </div>
               <div class="form-group">
                 <%= f.label :body %>
                 <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
               </div>
              
               
             
               <div class="form-group">
                 <%= f.submit "Save", class: 'btn btn-default' %>
               </div>
             <% end %>
             <% if current_user.Premium? || current_user.Admin? %>
             <%= render "collaborators/index" %> 
             <% end %>
           
     </div>
</div>

app/views/wikis/index.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="container">
        <h1>All Wikis</h1>
        <% @wikis.each do |wiki| %>
          <div class="media col-sm-4">
             <div class="media-body">
               <h4 class="media-heading">
                 <span><%= link_to wiki.title, wiki %></span>
               </h4>
             </div>
           </div>
        <% end %>
        </div>
    </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
    <div class="jumbotron">
        <h1>New Wiki</h1>
          <%= form_for @wiki do |f| %>
           <div class="form-group">
             <%= f.label :title %>
             <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
           </div>
           <div class="form-group">
             <%= f.label :body %>
             <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
           </div>
           <% if current_user.Admin? || current_user.Premium? %>
              <div class="form-group">
              <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
            </div>
            <% end %>
           <div class="form-group">
             <%= f.submit "Save", class: 'btn btn-default' %>
           </div>
          <% end %>
          
          <div>
         <%= link_to "Back", :back %>
         </div>
    </div>
     
 </div>

app/views/wikis/show.html.erb
<div class="container">
    <div class="jumbotron">
        <h1><%= @wiki.title %></h1>
          <% if @wiki.private == true %>
                 <span><h4>Private Wiki</h4></span>
        <% end %>
          <p><%= markdown(@wiki.body) %></p>
            <small>
              Submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %><br>
              
              Collaborators: 
              <% @wiki.collaborators.each do |collaborator| %>
               <%= User.find_by_id(collaborator.user_id).email %>,
               <% if current_user.Premium? || current_user.Admin? %>
               <%= link_to "Delete User", [@wiki, collaborator], class: 'btn btn-danger delete', method: :delete, data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
               <% end %>
              <% end %>
            </small>
            <br>
   
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-default' %>
     <% if current_user.Admin? || @wiki.user.email == current_user.email %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
     <% end %>
   </div>
   <div>
    <%= link_to "Back", :back %>
    </div>
 </div>